version: '3'

tasks:
  lint:
    desc: lint your helm chart
    cmds:
      - helm lint .
  spicylint:
    desc: lint your helm chart with kube-score and some other stuff
    cmds:
      - helm template . | kubeconform -strict
      - helm template . | kube-score score -
  docs:
    desc: generate documentation for your helm chart
    cmds:
      - helm-docs .
  template:
    desc: template your helm chart
    cmds:
      - helm template . > output/manifest.yaml
  dependency:
    desc: install dependencies
    cmds:
      - helm dependency update
  minikube:
    desc: Start minikube
    cmds:
      - minikube start --addons=ingress
    silent: true
    status:
      - test $(minikube status | grep -i running | wc -l) -eq 3
  minikube:down:
    desc: Bring down minikube
    cmds:
      - minikube stop
    silent: true
    status:
      - test $(minikube status | grep -i stopped | wc -l) -eq 4
  minikube:purge:
    desc: Run minikube delete
    cmds:
      - minikube delete
    silent: true
  install:
    desc: install dependencies related to this task file 
    cmds:
      - brew install helm
      - brew install kubectl
      - brew install kubeconform
      - brew install kubeaudit
      - brew install kube-score
      - task: krew
      - brew install norwoodj/tap/helm-docs
  krew:
    desc: install krew
    cmds: 
      - |
        set -x; cd "$(mktemp -d)" &&
        OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
        KREW="krew-${OS}_${ARCH}" &&
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
        tar zxvf "${KREW}.tar.gz" &&
        ./"${KREW}" install krew